# Generated by Django 2.2.4 on 2019-08-22 17:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0002_auto_20190820_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.CharField(choices=[('in', 'Check-in'), ('out', 'Check-out')], max_length=3)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vacation',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.Employee'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='checking',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetracker.Employee'),
        ),
    ]
