# Generated by Django 2.2.4 on 2019-08-22 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0003_auto_20190822_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checking',
            old_name='userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vacation',
            old_name='userid',
            new_name='user',
        ),
    ]
