# Generated by Django 2.2.4 on 2019-08-23 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0006_auto_20190823_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 8, 23, 16, 13, 34, 537783, tzinfo=utc)),
        ),
    ]
