# Generated by Django 2.2.4 on 2019-08-23 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0007_auto_20190823_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
