# Generated by Django 2.2.4 on 2019-08-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0009_auto_20190823_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workinghours',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
