# Generated by Django 2.2.4 on 2019-08-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0011_auto_20190827_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='checkin',
            field=models.DateTimeField(),
        ),
    ]
