# Generated by Django 2.2.4 on 2019-08-27 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0012_auto_20190827_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='checkout',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
