# Generated by Django 2.2.4 on 2019-08-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0013_auto_20190827_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='checkin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='checking',
            name='checkout',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
